export const UPDATE_ROOM_STATUS = "UPDATE_ROOM_STATUS";
export const UPDATE_ROOM_CURRENT_QUESTION = "UPDATE_ROOM_CURRENT_QUESTION";
export const UPDATE_ROOM_FINISHED_QUIZ = "UPDATE_ROOM_FINISHED_QUIZ";